all: compile

compile:
	javac Client_itf.java Client.java Irc.java Sentence.java Server_itf.java Server.java ServerObject_itf.java ServerObject.java SharedObject_itf.java SharedObject.java

run:
	java Irc bonjour

clean:
	rm -f *.class
